"""empty message

Revision ID: bec10bfa000a
Revises: 065aaf70b803
Create Date: 2025-04-06 19:18:51.767345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bec10bfa000a'
down_revision = '065aaf70b803'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('print_product_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('image', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('print_product_categories', schema=None) as batch_op:
        batch_op.drop_column('image')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
